### ISSUE TITLE
how to get the current running  aux jobs

### ISSUE THREAD

**Issue by sorin00** [Commvault/cvpysdk#101]
hello , 

How can I get the current running aux jos?

thanks
Sorin

**Comment by spakhare** [comment]
Hi @sorin00 ,

Can you please try using the below API?
https://github.com/Commvault/cvpysdk/blob/master/cvpysdk/job.py#L652

commcell_object.job_controller.active_jobs(job_filter='AUXCOPY')

Thanks,

**Comment by sorin00** [comment]
the function is correct , but is not working with that filter .
do you know where do I find the right parameter for job_filter or job type ?

**Comment by spakhare** [comment]
The below link has details on all the acceptable job filter values. All the values are case sensitive.
https://documentation.commvault.com/commvault/v11/article?p=105923.htm

**Comment by sorin00** [comment]
but the AUXCOPY is not working .
can we do something ?
can we have some alternative filter ?

**Comment by spakhare** [comment]
We might have to look into the logs for this. Can you please create a commvault support ticket for this?
You can email to support@commvault.com.

**Comment by sorin00** [comment]
but can you confirm that is not working ?

**Comment by spakhare** [comment]
Also, did you try adding greater lookupTime. By default, we look for job details for the last hour.
https://github.com/Commvault/cvpysdk/blob/master/cvpysdk/job.py#L652

Ideally, it should work. To check why it is not working for you we need to check logs on your setup.

**Comment by sorin00** [comment]
k,
thanks
