### ISSUE TITLE
backup an sql server instance with copyonly option

### ISSUE THREAD

**Issue by sorin00** [Commvault/cvpysdk#104]
hi , 

I try to backup an sql server instance with copyonly option like this :
subclient.backup(backup_level=r'full', data_options=['CopyOnly']) 
This is not working .
Can you tell me why ?

thank
sorin

**Comment by spakhare** [comment]
Hi @sorin00 ,

You are passing an incorrect list item here. The correct item to pass is **copy_only**. You can get the acceptable list values from the method docstrings.
https://github.com/Commvault/cvpysdk/blob/master/cvpysdk/subclients/sqlsubclient.py#L201

Thanks

**Comment by sorin00** [comment]
thanks
you can close the ticket 
sorin00
