### ISSUE TITLE
browse an sql server subclient

### ISSUE THREAD

**Issue by sorin00** [Commvault/cvpysdk#105]
hello , 

when I try to browse the sql server subclient I got an error message:
paths, details_dict = subclient.browse()
AttributeError: 'SQLServerSubclient' object has no attribute 'browse'

the file system is working fine.

how can I browse an sql server subclient ?
thanks
sorin00

**Comment by Vairavaprakash** [comment]
Hi sorin00,

For SQL Server we do not support browse or restore from subclient level.

can you please try browse from instance level?

Regards
VP
