### ISSUE TITLE
Error while accessing API

### ISSUE THREAD

**Issue by dhikss** [Commvault/cvpysdk#107]
Hello,

I am using Comvault API to get the "Subclient properties" . I am using it as below , but getting error for the same. Please let me if i am using it incorrectly.

http://cmsvlab001win/webconsole/api/Group3-me07/196

headers = {'authtoken': '{token valur}','accept': "application/json"}

**Comment by spakhare** [comment]
Hi @dhikss,

Please refer below link to get API details on subclient properties and other subclient related operations.
https://api.commvault.com/#aa17e8fb-1cc8-48ea-9eb8-8068b0d28f3e

Thanks.
