### ISSUE TITLE
Restore using a VMware subclient with VM names and folders is not supported 

### ISSUE THREAD

**Issue by pertoft** [Commvault/cvpysdk#108]
I have received a confirmation from dev that its not possible to perform a restore using a VMware subclient containing a vm and a vcenter folder. This is a feature request, and therefor I have opened this github feature request.

Incident Update: 200901-177
CVLT::0331051478

Currently SDK doesn’t support vcenter folder + vms in the same subclient for restores.
Supported scenario is to have either vms or the vcnter folder in the subclient.

 
I received feedback from CommVault Development and an official Modification Request number 292909 has been generated and is now considered a Software Enhancement, which will be addressed through a CommVault software design change moving forward.

**Comment by spakhare** [comment]
Ticket addressed by with the Commvault support team's help. Closing this issue.
