### ISSUE TITLE
PDF format for BackupJobSummary report doesn't work

### ISSUE THREAD

**Issue by rantanevich** [Commvault/cvpysdk#111]
Hi!

I would like to generate a backup job summary report in pdf format, but I take the report in html format everytime. 
I am using next snippet:

```python
from cvpysdk.commcell import Commcell
from cvpysdk.reports.report import BackupJobSummary, FormatType

commcell = Commcell('commserve', 'admin', 'secret')

report = BackupJobSummary(commcell)
report.set_format(FormatType.PDF)
report.select_local_drive('C:\\')
report.set_last_hours(24)
report.run_report()
```

I have tried to use all available options (HTML, PDF, TEXT, XML), but I always take only html format.

**Comment by Dfrancis-20** [comment]
@rantanevich, This issue has been fixed with latest release this week, please try with latest code changes.

**Comment by rantanevich** [comment]
@Dfrancis-20 , All right. Thank you!
