### ISSUE TITLE
Fetching configuration information from decoupled client install

### ISSUE THREAD

**Issue by asshutossh** [Commvault/cvpysdk#113]
Trying to create pseduo clients using commcell.clients.create_pseudo_client(client_name)

There is no flag to have the configuration information read from the client using a specific cvd port. This is the case when the client has already been installed in decoupled mode.

What needs to be done next to have the client registered with the commcell?

**Comment by spakhare** [comment]
Hi @asshutossh ,

create_pseudo_client() is used to create a new client and hence cannot be used to register a decoupled client.

We have introduced a new API to register decoupled clients. Can you please try using that?
https://github.com/Commvault/cvpysdk/blob/dev/cvpysdk/client.py#L818
