### ISSUE TITLE
Create pseudoclient

### ISSUE THREAD

**Issue by lucassouto** [Commvault/cvpysdk#115]
Is it possible to add the option of passing `client_hostname` as a parameter to the [create_pseudo_client](https://github.com/Commvault/cvpysdk/blob/master/cvpysdk/client.py#L750) method instead of using `client_name` as hostname? If so, I can open a PR myself to add this feature.

**Comment by spakhare** [comment]
Hi @lucassouto,

Yes, we can add an optional parameter to take client_hostname. 

Can you please submit a PR on the dev branch?

Thanks,
Sachin

**Comment by spakhare** [comment]
Hi @lucassouto,

We have included this support in our dev branch. 
https://github.com/Commvault/cvpysdk/blob/dev/cvpysdk/client.py#L758

Thanks
