### ISSUE TITLE
Documentation lacks complete list of possible job states

### ISSUE THREAD

**Issue by stuartm** [Commvault/cvpysdk#116]
The documentation, and so far as I can tell the SDK code lacks a complete listing of all the possible values for Job State. The documentation just says "(Completed / Suspended / Waiting / … / etc.)".

This list **is** available in the REST API documentation if you know to look there but I would suggest it would help to have this information in in the SDK documentation, or at least a link to relevant section of the API documentation, alongside the job.status entry. This is already done for the values of job_filter.

**Comment by spakhare** [comment]
Hi @stuartm,

We have updated our docstrings and included a link to all the possible job status. It is now available on our dev branch.
https://github.com/Commvault/cvpysdk/blob/dev/cvpysdk/job.py#L2210

Thanks
