### ISSUE TITLE
Add sendEmail parameter when creating organizations

### ISSUE THREAD

**Issue by eglute** [Commvault/cvpysdk#121]
Currently, when creating organizations, there is no option to set `sendEmail` parameter. Please add `sendEmail` as an optional parameter to https://github.com/Commvault/cvpysdk/blob/master/cvpysdk/organization.py#L327.
For example, postman scripts in this repo have it: https://github.com/Commvault/VMC-AWS-Automation

```{
    "organizationInfo": {
        "organization": {
            "connectName": "{{connectName}}",
            "emailDomainNames": [
                "{{emailDomainNames}}"
            ],
            "shortName": {
                "domainName": "{{companyName}}"
            }
        },
        "organizationProperties": {
            "primaryDomain": "",
            "primaryContacts": [
                {
                    "fullName": "{{fullName}}",
                    "email": "{{email}}"
                }
            ]
        }
    },
    "sendEmail": false
}
```

**Comment by iamthemananiket** [comment]
@eglute , Thanks for mentioning this. We'll add the _sendEmail_ support as soon as possible.

**Comment by eglute** [comment]
Thanks @iamthemananiket, any updates on when this will be updated?

**Comment by spakhare** [comment]
Hi @eglute, 
This fix should be available by Monday on the dev branch.

**Comment by eglute** [comment]
This is still not fixed, 
```
"sendEmail": false
```
needs to be part of the organizationInfo json. 
```
request_json = {
            'organizationInfo': {
                'organization': {
                    'connectName': name,
                    'emailDomainNames': email_domain,
                    'shortName': {
                        'domainName': company_alias
                    }
                },
                'organizationProperties': {
                    'enableAutoDiscovery': enable_auto_discover,
                    'primaryDomain': primary_domain,
                    'primaryContacts': [
                        {
                            'fullName': contact_name,
                            'email': email
                        }
                    ],
                    'defaultPlans': plans_list
                }
            },
            "sendEmail": False
        }
       
```
if it is set to False by default it is not updated at all in `organizationInfo` and I still get SMTP error.

**Comment by eglute** [comment]
@iamthemananiket and @spakhare I tested this in the dev branch, still not fixed. Thank you.

**Comment by spakhare** [comment]
@iamthemananiket 
Can you please check this?

**Comment by iamthemananiket** [comment]
@eglute , Could you please share the following details - 
1. The current service pack of your Commcell.
2. The arguments that you are passing to the `add()` function in organization.py
3. The error(s) that are being seen when you attempt this operation.

**Comment by eglute** [comment]
Version:  11.20.27

This is the request json that gets built right before POST call is made:
```
{
    'organizationInfo': {
        'organization': {
            'connectName': 'vcenter.sddc.vmwarevmc.com',
            'emailDomainNames': ['vcenter.sddc.vmwarevmc.com'],
            'shortName': {
                'domainName': 'vcenter.sddc.vmwarevmc.com'
            }
        },
        'organizationProperties': {
            'enableAutoDiscovery': False,
            'primaryDomain': '',
            'primaryContacts': [{
                'fullName': 'vcenter.sddc.vmwarevmc.com',
                'email': 'egle@foo.com'
            }],
            'defaultPlans': []
        }
    }
}
```
This is the error I get: 
```
Traceback (most recent call last):
  File "commvault_client.py", line 133, in <module>
    main()
  File "commvault_client.py", line 105, in main
    comm.create_customer(name)
  File "commvault_client.py", line 29, in create_customer
    email_domain=[email_domain], send_email=False)
  File "/python3.6/site-packages/cvpysdk/organization.py", line 488, in add
    'Organization', '107', 'Error: "{0}"'.format(response.json()['errorMessage'])
cvpysdk.exception.SDKException: Failed to add organization
Error: "By SMTPClient: Syntax error in parameters or arguments. The server response was: 5.1.7 Bad sender address syntax"

Process finished with exit code 1
```
So it looks like it's still trying to send an email by default. It doesn't do that if change the request_json to have `"sendEmail": False` at the end.

**Comment by iamthemananiket** [comment]
@eglute , Thanks. We are trying to reproduce this issue internally.

**Comment by iamthemananiket** [comment]
@eglute , We will need to inspect this further from the server end.
Request you to please contact support@commvault.com with details about the issue.

**Comment by eglute** [comment]
Thanks @iamthemananiket. I have this fixed locally so that I do not get an error. Would you like a pull request? I am also sending an email to support.

**Comment by eglute** [comment]
@iamthemananiket commvault does not provide support via email.

**Comment by iamthemananiket** [comment]
Hi @eglute, could you please confirm if you are still seeing the issue.
Also, did you get a chance to contact customer support?

**Comment by spakhare** [comment]
Hi @eglute,
As we need logs for further analysis we couldn't help you here. Please reopen this issue if got some help from support or need our help with support ticket creation.

Thanks
