### ISSUE TITLE
Unable to backup a filesystem (subclient content issue)

### ISSUE THREAD

**Issue by Amine-hml** [Commvault/cvpysdk#122]
Hello,

I'm trying to backup a filesystem from a storage array, I noticed that the update of the subclient content using this syntax : 

`subclient.content = ["My_storage_array:/My_Filesystem"]`

This syntax is not executed correctly, we can write anything in the content even if it is not present in the storage array, no validation is done by commvault.

The output of the backup job fails and returns the following error: 

`"File system scan failed - there is nothing to back up. A possible cause is that none of the subclient contents exist.".`

the code that i'm using to do my backup is bellow : 

`commcell = Commcell('My_commcell', commcell_login ,commcell_password)`
`client = commcell.clients.get('My_storage_array')`
`agent = client.agents.get('My_Agent')`
`backupset = agent.backupsets.get('My_Backupset')`
`backupset.subclients.add("backup_tmp", storage_policy="My_storage_policy")`
`subclient = backupset.subclients.get("backup_tmp")`
`subclient.content = ["My_storage_array:/My_Filesystem"]`
`subclient.enable_backup()`
`job_backup = subclient.backup(backup_level='Full')`

Thank you in advance for your answers.

**Comment by spakhare** [comment]
Hi @Amine-hml,

Can you please drop an email to support@commvault.com? We might have to look at the logs to get more details.

Thanks

**Comment by Amine-hml** [comment]
Hi @spakhare,

I sent an e-mail to the commvault support before opening this issue because they asked me to do so.

Thank you,

Amine

**Comment by spakhare** [comment]
Hi @Amine-hml,

Can you please share the support ticket number you had created? Maybe we can take it forward from there?

Thanks

**Comment by spakhare** [comment]
Hi @Amine-hml,

Can you please share the support ticket you had created? That would help us gather more details on this issue.

Thanks

**Comment by Amine-hml** [comment]
Hi @spakhare,

i found the solution via commvault community, my code as missing this line of code,

`subclient.network_share_auto_mount = True`

hope it will help someone in the futur,

Thanks for your help,

Amine
