### ISSUE TITLE
Error handling when creating organization

### ISSUE THREAD

**Issue by eglute** [Commvault/cvpysdk#123]
Currently, when creating organization, if one of the inputs is incorrect, the error returned is only 
```
'101': 'Data type of the input(s) is not valid',
```
Instead of specifying which of the inputs is invalid. For example, `email_domain` when adding organization should be a list, but if a single email is passed, the message returned doesn't specify which field out of 10 possible was incorrect.

**Comment by spakhare** [comment]
Hi @eglute,

That is by the design of this module. We are expecting users to refer to the method docstrings to get the details on the user input. That would give them more details on the expected output and possible exception scenarios.

Thanks

**Comment by eglute** [comment]
Hello @spakhare it might be by design, but if I am passing 10 inputs, it would be very helpful to know which field failed validation.

**Comment by spakhare** [comment]
Hi @eglute,

I might not be able to make this change immediately but we can look at possibilities in future updates. Thanks for your feedback on this.

Thanks

**Comment by eglute** [comment]
Thank you @spakhare!
