### ISSUE TITLE
Unable To restore filesystems - cvpysdk - Python

### ISSUE THREAD

**Issue by Amine-hml** [Commvault/cvpysdk#124]
Hello,

I have some trouble to restore filesystems to a Storage array using the cvpysdk python library, the restore from the Commcell works perfectly.

The commands that i’m using to do a restore is bellow:

```
commcell = Commcell('My_commcell', commcell_login ,commcell_password)
client = commcell.clients.get('My_storage_array')
agent = client.agents.get('My_Agent')
backupset = agent.backupsets.get('My_Backupset')
backupset.subclients.add("backup_tmp", storage_policy="My_storage_policy")
subclient = backupset.subclients.get("backup_tmp")
subclient.network_share_auto_mount = True
subclient.content = ["My_storage_array:/My_Filesystem"]
subclient.enable_backup()
job_backup = subclient_fs.backup(backup_level='Full')
job_finished =job_backup.wait_for_completion()
paths_retore = "/My_storage_array/My_Filesystem"
job_restore = subclient_fs.restore_out_of_place(client="My_Client", paths=[paths_retore],destination_path="/My_storage_array")
```

the job is always pending and it detectes the number of files and folders to restore, the output is :

```
job_restore.pending_reason

'Failed to restore even a single file<br>Source: My_Client, Process: clRestore'
```

is there any command or anything that i’m missing ?

Thanks in advance for your help

Amine

**Comment by spakhare** [comment]
Looks like this is taken care here on Commvault Community Forum.
https://community.commvault.com/technical-q-a-2/unable-to-restore-filesystems-cvpysdk-python-320
