### ISSUE TITLE
Get all clients filtered by agent type

### ISSUE THREAD

**Issue by rantanevich** [Commvault/cvpysdk#126]
Hi,

Is there opportunity to get all client filtered by agent type? For instance, I'd like to take all Oracle agents.

I found a function that could do this in theory. Could you clarify all available `url_params` options or advice another way?

https://github.com/Commvault/cvpysdk/blob/56d878377b06d9a068cd89a917cc2622647f5193/cvpysdk/client.py#L4741-L4759

**Comment by iamthemananiket** [comment]
Hi. We'll soon be adding support for retrieving the list of clients of a particular agent type.
-Thanks

**Comment by rantanevich** [comment]
Thank you! Can you say it will be added in SP23 or next SP?

**Comment by iamthemananiket** [comment]
We'll let you know as soon as it is ready.
Until then please see if you can try this work around to retrieve the clients of a particular agent -

```
# Create a Commcell object and use the [request()](https://github.com/Commvault/cvpysdk/blob/56d878377b06d9a068cd89a917cc2622647f5193/cvpysdk/commcell.py#L1483) function in Commcell class to make request

#In this example applicationId - 22 is for Oracle agents
resp = cc_obj.request('GET', 'applicationId=22')

#The json() function will return the response as a dictionary
resp.json()
```
Please let us know the specific agents that you want to filter and retrieve. We can share with you it's respective applicationid.

**Comment by rantanevich** [comment]
Yep, it works fine. 
I'd like to know AppId for file system (Linux, Windows) and database (PostgreSQL, MySQL, SQL).

**Comment by iamthemananiket** [comment]
Please try these values -

Agent | ApplicationId
-- | --
Windows File System | 33
Unix File System | 29
PostgreSQL | 125
MySQL | 104
MS SQL | 81

**Comment by rantanevich** [comment]
Great! All values are correct. Thank you!
