### ISSUE TITLE
Incorrect check in vmware.py

### ISSUE THREAD

**Issue by zaeem-suhail** [Commvault/cvpysdk#127]
In file cvpysdk/cvpysdk/subclients/virtualserver/vmware.py for the **full_vm_restore_in_place()** function the check on line 144 is incorrect. this checks whether the variable, **_vm_to_restore_**, is a string instead of a list which causes it to fail on line 161 because the function **_set_vm_to_restore()** in cvpysdk/cvpysdk/subclients/vssubclient.py requires the variable, **_vm_to_restore_**, to be a list. The function then tries to loop through the string on line 1862 which raises an **SDKException('Subclient', '104');**

incorrect line:

```
if vm_to_restore and not isinstance(vm_to_restore, basestring):
     raise SDKException('Subclient', '101')
```

correct line: 

```
if vm_to_restore and not isinstance(vm_to_restore, list):
     raise SDKException('Subclient', '101')
```

Please make this change as soon as possible.

Thank you

**Comment by kneerudge** [comment]
Hi @zaeem-suhail ,

To Have this fix on the master branch, Can you please raise a ticket by sending mail to support@commvault.com

**Comment by zaeem-suhail** [comment]
> Hi @zaeem-suhail ,
> 
> To Have this fix on the master branch, Can you please raise a ticket by sending mail to [support@commvault.com](mailto:support@commvault.com)

Hey @kneerudge 

I just sent them an email, what is the turn around time for something like this?

**Comment by zaeem-suhail** [comment]
@kneerudge 

I just got a response from them, this is what they wrote;

"Unfortunately, Commvault Customer Support no longer supports the processing of cases/tickets through e-mail. This is a decision that has been handed down from upper management."

**Comment by kneerudge** [comment]
Hi @zaeem-suhail,

Please use the following portal to raise the ticket https://ma.commvault.com/

**Comment by zaeem-suhail** [comment]
Hey @kneerudge 

I cant, I don't have an account! 

Can I make the change in dev and create a pull request?

**Comment by kneerudge** [comment]
Hi @zaeem-suhail 

Can the dev branch be used here?
In file cvpysdk/cvpysdk/subclients/virtualserver/vmware.py, on line 148: 
        if vm_to_restore and not isinstance(vm_to_restore, basestring):
            raise SDKException('Subclient', '101')
            
on line 160 :
        if vm_to_restore:
            vm_to_restore = [vm_to_restore]

This will take the vm_to_restore as a string and later convert it into the list

**Comment by zaeem-suhail** [comment]
Hey @kneerudge 

What this does is it prevents restoring multiple vm's... it only allows for either all vm's in a subclient or just one vm to be restored. It is much cleaner and simpler to modify the incorrect check.

**Comment by zaeem-suhail** [comment]
Hey @kneerudge 

Any idea when dev will be merged with Master?

**Comment by zaeem-suhail** [comment]
Any idea when dev will be merged with Master? @Vairavaprakash

**Comment by kneerudge** [comment]
Hi @zaeem-suhail 

The above change is now merged with the master branch.
