### ISSUE TITLE
Access to Subclient Policies

### ISSUE THREAD

**Issue by kivengh** [Commvault/cvpysdk#128]
Hi,
Is it possible to access to Subclient Policies through  cvpysdk ?

Regards

**Comment by spakhare** [comment]
Hi @kivengh,

As of now, we don't have support to add/view subclient policies through cvpysdk. 

Thanks

**Comment by spakhare** [comment]
Hi @kivengh,

We do have support for plans via cvpysdk. Is it possible to use plans? 
If plans don't work for you, please let us know the use cases where the subclient policy is being used.

**Comment by spakhare** [comment]
Reopen the issue if you have any other queries.
