### ISSUE TITLE
protected_vms()

### ISSUE THREAD

**Issue by LittleOneChewy** [Commvault/cvpysdk#129]
`cvpysdk.commcell.Commcell.protected_vms()` returns only first 100 records

to avoid this, i edited `services.py` file and changed request to:
`'PROTECTED_VMS': "{0}VM?propertyLevel=AllProperties&status=1&fromTime=%s&toTime=%s&Limit=100000",`

please, make an option to select page (&start&limit) or just to set limit (&limit)

**Comment by spakhare** [comment]
This has been fixed on the dev branch. 
https://github.com/Commvault/cvpysdk/blob/dev/cvpysdk/commcell.py#L1907
