### ISSUE TITLE
Search entities by id

### ISSUE THREAD

**Issue by kevin-menon-EDF** [Commvault/cvpysdk#130]
In order to have a specific commvault object, you must navigate through the parent entities from the commcell object.
It would be practical to access an object by its id.

For example:
```python
client = commcell.clients.get("my_vcenter")
agents = client.agents.get("my_agent")
instance = agents.instances.get("my_instance")
subclient = instance.subclients.get("my_subclient")
```
could be:
```python
subclient = commcell.get_subclient(1)
```
This issue could be linked to https://github.com/Commvault/cvpysdk/issues/85

**Comment by spakhare** [comment]
Currently, this is not supported by design. But if you are looking for creating entity objects directly you might have to call API directly.

**Comment by kevin-menon-EDF** [comment]
Is there a way I can transform my API request to a cvpysdk object ?

For example:
```python
subclient_id = 1
response = commcell.request(f'/Subclient/{subclient_id}')
subclient = Subclient(response.json())
```

The class signature for Subclient requires a Backupset object, so it seems there is no way to instanciate it without navigation unless I am mistaking? 

Many thanks for your answer

**Comment by spakhare** [comment]
Hi @kevin-menon-EDF,

Yes, you are correct, we require a backupset object for creating a subclient class. As of now, we cannot create a Subclient class using the API response.

Thanks
