### ISSUE TITLE
File System/Subclient

### ISSUE THREAD

**Issue by dirtyharrycallahan** [Commvault/cvpysdk#134]
Is there a way to clear filter_content in a subclient? We have a complex application and are using the CVPySDK, great tool btw, to update the content and the filter_content then starting backup jobs and monitoring them. Seems filter content does not like an empty list or None.

**Comment by spakhare** [comment]
This has been fixed with the latest change on the dev branch. 
https://github.com/Commvault/cvpysdk/blob/dev/cvpysdk/subclients/fssubclient.py#L491

**Comment by dirtyharrycallahan** [comment]
I looked at the changes and with holidays just getting around to updating our cvpysdk code. Seems to work as desired, passing an empty list instead of having to add "__dummy__" content.
