### ISSUE TITLE
The Subclient default is configured to show all unprotected VMs in the / folder from vmware.

### ISSUE THREAD

**Issue by pertoft** [Commvault/cvpysdk#138]
The Subclient default is configured to show all unprotected VMs in the / folder from vmware.

However, when I access the folder using the SDK with:
```
self.__subclient = self.__commcell.clients.get(self.__config['vmware']['vcenter']).agents.get('virtual server').instances.get('vmware').backupsets.get(self.__config['vm']['backupset']).subclients.get("default")
ids, vmproperties = self.__subclient.browse()
```
The response (ids, vmproperties) are empty.
How is it possible to list all VMs from the client (like the preview button in commvault)?

**Comment by spakhare** [comment]
Please try with the latest changes
