### ISSUE TITLE
full_vm_restore_out_of_place proxy_client argument ignored

### ISSUE THREAD

**Issue by pertoft** [Commvault/cvpysdk#139]
`
subclient = commcell.clients.get("vc01.example.com").agents.get('virtualserver').instances.get('vmware').backupsets.get('defaultBackupSet').subclients.get('testclient')

job = subclient.full_vm_restore_out_of_place(
vm_to_restore="test.example.com",
overwrite=False,
power_on=False,
proxy_client="commproxy01"
)`
The proxy_client is not used, and the default media agent will be used

**Comment by spakhare** [comment]
Please try with the latest changes
