### ISSUE TITLE
Docs removed

### ISSUE THREAD

**Issue by mattmorganpdx** [Commvault/cvpysdk#142]
I'm actively developing an integration and noticed the docs disappeared.
This seems to be intentional?
https://github.com/Commvault/cvpysdk/commit/ff8f4ee2aa76be65b35be118a7c872e6414f4a01

As a result links like this do not work anymore
https://commvault.github.io/cvpysdk/cvpysdk/commcell.html

I can pull down the old sha and self host but I think you want to fix this.

**Comment by kevinjojeejoseph** [comment]
Hi @mattmorganpdx 
We had a few issues with the documentation and we were reconfiguring it. Please check the updated documentation now
