### ISSUE TITLE
how i fetch the data form commvault backup report SDK

### ISSUE THREAD

**Issue by divyanshu3004** [Commvault/cvpysdk#143]
I'm trying to fetch the my backup report which show in the Commcell dashboard when i login the there is option of report but when I'm trying to fetch this report via SDK I'm not able to fetch can you help me out I'm new here. 

Thanks in advance

**Comment by vinudass** [comment]
Hi, BackupJobSummary sdk is to trigger a backup job summary report job.

Sample:
self.commcell --> commcell object

        reports = self.commcell.reports
        reports.backup_job_summary.select_local_drive(<path in CS>)
        reports.backup_job_summary.select_protected_objects()
        reports.backup_job_summary.set_report_custom_name(self.report_custom_name)
        job_id = reports.backup_job_summary.run_report()
        job_obj = self.commcell.job_controller.get(job_id)
        job_obj.wait_for_completion()
 
 to fetch report data directly from reports in webconsole or command center you can refer information in below link to get its corresponding REST API.
 https://documentation.commvault.com/11.24/essential/115149_copying_dataset_id_from_reports.html

**Comment by divyanshu3004** [comment]
I run this code ,I got report in commvault machine **path(C:\Program Files\Commvault\ContentStore\Reports)** . But i want backup report in python variable,is this possible?

**Comment by spakhare** [comment]
Hi @divyanshu3004,

backup_job_summary object in the below lines represents the backup job summary report object. 

reports = self.commcell.reports
reports.backup_job_summary

Thanks
