### ISSUE TITLE
Creating a subclient (File System) without a storage policy

### ISSUE THREAD

**Issue by jbeimler** [Commvault/cvpysdk#147]
Our team is currently experimenting moving from q scripts to using the API via the cvpysdk module to ease the transition.

One of the qoperation scripts we utilize creates adds subclients without a storage policy so that it inherits the storage policy from client computer group. 

When trying to replicate this with the cvpysk the code throws an exception, as the subclient add function requires that a storage policy be a string and exist on the commserve.

https://github.com/Commvault/cvpysdk/blob/fbcbb183d2c66c4156a2b9aa1e5a17b245866a3f/cvpysdk/subclient.py#L726

Are there suggestions on how to replicate our current scripts actions using the cvpysdk module?

**Comment by kevinjojeejoseph** [comment]
Hi @jbeimler 
the dev branch has a change that will allow you to pass None to the add method for StoragePolicy
https://github.com/Commvault/cvpysdk/blob/da62aefa3dd7e4774421a075e0969605fd032c3d/cvpysdk/subclient.py#L544
Please re-open if this does not help
