### ISSUE TITLE
get(name).update_associations does not work properly

### ISSUE THREAD

**Issue by abadrilov** [Commvault/cvpysdk#150]
Hello. 
I have written the code that delete agent from schedules policy. 
I seem that update_associations(lst, "deleted") does not work properly.
For example, let's take Postgresql agent that has two backupset. usually, we use one of it DumpBase or FSBase. When in schedules policy selected DumpBase and FSBase update_associations(lst, "deleted") works fine. When  in schedules policy seleted one of DumpBase or FSBase update_associations(lst, "deleted") does not work.

Could you check that please?

**Comment by spakhare** [comment]
Hi @abadrilov,

Can you please create a support ticket for this? We might need log access for this. Can you please write to support@commvault.com with all these details and also include your script that failed for our reference?

Thanks
