### ISSUE TITLE
Cancel lowercase namings

### ISSUE THREAD

**Issue by kevin-menon-EDF** [Commvault/cvpysdk#151]
In our workflows, we often set inputs and variables of clients/backupsets/subclients etc. 

However we have a naming convention and it would be better if the naming of the entity would be as wanted when creating it through the .add() method.
Unfortunately, cvpysdk currently lowers the backupset values.
For example here:
https://github.com/Commvault/cvpysdk/blob/master/cvpysdk/backupset.py#L481

Also, the add() method for clientgroups.py lowers the client names with the _valid_clients() method:
https://github.com/Commvault/cvpysdk/blob/0e5e97c7d66e41782ea24f8215bcc17679c264d1/cvpysdk/clientgroup.py#L281

It is also the same for getting a clientgroup:
https://github.com/Commvault/cvpysdk/blob/0e5e97c7d66e41782ea24f8215bcc17679c264d1/cvpysdk/clientgroup.py#L765

This makes us use the commvault api directly for these cases through cvpysdk.request()

Would it be possible to cancel that or would there be too potential side-effects?

**Comment by spakhare** [comment]
Hi @kevin-menon-EDF,

It might be regressive to cancel lowercase for names. Using lowercase everywhere makes it easier for us to support case-insensitive names.

But for such scenarios, we have added display_name for the client and a few other entities. Can you please check if you can use those?
https://github.com/Commvault/cvpysdk/blob/master/cvpysdk/client.py#L3718
https://github.com/Commvault/cvpysdk/blob/master/cvpysdk/clientgroup.py#L1215

Thanks,
Sachin
