### ISSUE TITLE
2022E/11.28 release?

### ISSUE THREAD

**Issue by mvangoor** [Commvault/cvpysdk#152]
Hi Commvault development/engineering team,

We recently upgraded to 2022E(11.28) and ran into the name change as announced here:
https://documentation.commvault.com/2022e/essential/149399_changes_in_commvault_platform_release_2022e.html

Our complete orchestration/automation is broken because of this.

We noticed the `dev` branch has fixes for this already and we would like to understand why there was no release of cvpysdk for 2022E/11.28?

We cannot use the dev branch in our pipelines/automation and would really like to get a official release out asap if possible.

Thanks!

**Comment by kevinjojeejoseph** [comment]
Hi,
We have released 11.28. Apologies for the delay
Thanks
