### ISSUE TITLE
Question about UnixCluster

### ISSUE THREAD

**Issue by abadrilov** [Commvault/cvpysdk#154]
Hello. 
I did not find in code any information about create Unix Cluster client. 
is it possible the create unix cluster client and add servers and agent for example Oracle to the unix group?
Next question about SVM Netapp.
SDK allow added to SVM from Netapp array to client?

**Comment by spakhare** [comment]
Hi @abadrilov,

This requires some new enhancements to the SDK. Can you please create a support ticket for this?
You can reach out to support@commvault.com for this.

Thanks.

**Comment by abadrilov** [comment]
Hi @spakhare 
Unfortunately no, because my contract was be expired one week ago. New contract will be after one month.
