### ISSUE TITLE
plan should override storage_policy requirement in cloudapps instance creation

### ISSUE THREAD

**Issue by mvangoor** [Commvault/cvpysdk#159]
Hi,

Please see https://github.com/Commvault/cvpysdk/blob/dev/cvpysdk/instance.py#L1120-L1131

The logic here demands storage policy to be set, but it is optional if plan is provided, or at least should be.
The code logic needs a refactor to allow the part below at https://github.com/Commvault/cvpysdk/blob/dev/cvpysdk/instance.py#L1150-L1153

to override storage policy.

**Comment by tejaKing123** [comment]
Hi, Can you please confirm in which SP you are trying this?

**Comment by mvangoor** [comment]
Hi @tejaKing123,

We are working with 11.30 (2023) currently.

**Comment by mvangoor** [comment]
Hello @tejaKing123, I do not understand the question as it should be generic for any cloud storage instance type as in Command Center there is no concept of storage policies only plans.

That said we are using it for Amazon RDS currently.

**Comment by mvangoor** [comment]
Hello @tejaKing123, can you share an update?

**Comment by mvangoor** [comment]
@tejaKing123 the update looks good, thanks for picking this up!
