### ISSUE TITLE
Request body is empty or format is invalid.

### ISSUE THREAD

**Issue by schumijo** [Commvault/cvpysdk#165]
When starting a SQL server restore using toTime option, I have the following error :
_Request body is empty or format is invalid._

There is a typo in sqlinstance.py : 
`"toTimeValue": to_time `
should be 
`"toTime" : to_time`

**Comment by twentynine30s** [comment]
The current expectation here is toTimeValue with format 'YYYY/MM/DD HH:MM:SS'. 

I will take this as an enhancement to accept both toTime and toTimeValue in future release.

**Comment by garcichr** [comment]
> When starting a SQL server restore using toTime option, I have the following error : _Request body is empty or format is invalid._
> 
> There is a typo in sqlinstance.py : `"toTimeValue": to_time ` should be `"toTime" : to_time`

The current expectation here is toTimeValue with format 'YYYY/MM/DD HH:MM:SS'.

I will take this as an enhancement to accept both toTime and toTimeValue in future release.
