### ISSUE TITLE
How to get backup status of a VM?

### ISSUE THREAD

**Issue by fakealiens** [Commvault/cvpysdk#166]
Is there anything in the python SDK related to the REST API: [GET Virtual Machines](https://documentation.commvault.com/11.24/essential/125353_rest_api_get_virtual_machines.html)

I need backup status of clients.

**Comment by spakhare** [comment]
Hi @fakealiens,

Can you please try using below method?
https://github.com/Commvault/cvpysdk/blob/master/cvpysdk/commcell.py#L2026

Thanks,
