### ISSUE TITLE
How to get last backup status of a client - anything available in REST/SDK?

### ISSUE THREAD

**Issue by fakealiens** [Commvault/cvpysdk#169]
I'm using following code to get all our clients. I just want the last back up status of the client. 
```
from cvpysdk.commcell import Commcell
commcell = Commcell(webconsole_hostname, commcell_username, commcell_password, authtoken=None, force_https=False, certificate_path=None, is_service_commcell=None)
```

I'm not able to find anything in Python SDK and REST API reference document to get last back up status of clients. However, in web console we can check like this - 
![image](https://github.com/Commvault/cvpysdk/assets/96639387/de50fbf7-6053-4618-8c22-0cd981fcf84a)

**Comment by spakhare** [comment]
Hi @fakealiens,

If you are looking for last backup time value, we can get that from agent properties. 

For example, check below image.

![image](https://github.com/Commvault/cvpysdk/assets/24286741/f6ff75fd-fc93-48bf-98da-00d14c1e8590)

**Comment by spakhare** [comment]
Hi @fakealiens,

We are using the GET agent properties API here. You can find more details about this API below.
https://documentation.commvault.com/v11/essential/45621_rest_api_get_agent.html

Thanks,
