### ISSUE TITLE
Getting error after After commvault upgrade

### ISSUE THREAD

**Issue by computeroregano** [Commvault/cvpysdk#170]
Hi,

We had automated the process of creating a vm group for a hypervisor for AWS, this was working for new AWS that were never configured with commvault before, but after we upgraded commvault to the latest version, our script failed while executing `subclient._process_add_request(json_request)` on a new AWS account with the following error:

```
raise SDKException('Response', '101', self._update_response_(response.text))
cvpysdk.exception.SDKException: Response was not success
},"errorMessage":"The [AWS-Plan-Development] plan is an Elastic Plan. To select this plan, associate the client to a region.","errorCode":587206437
```

We noticed that the Workload region wasn't set in the admin console of Commvault (Under Virtualization/Hypervisors) for this new account, which was done automatically before. So after setting this option and rerunning our script, our script could finish the setup successfully.

![adminConsoleRegion png](https://github.com/Commvault/cvpysdk/assets/135759034/289a3e35-b25a-49d1-ad77-87e8453518d5)

We instantiated the Commvault client, and we could verify that the region was already assigned on the client like this:

```
hypervisor = commcell.clients.get("our-new-aws-client")
client_props = hypervisor.properties
client_props.get('clientProps', {}).get('clientRegionInfo', {})
```
Which would give us: `{'region': {'regionId': 63, 'displayName': 'Europe (Ireland)', 'regionName': 'eu-west-1'}}`

Was there any change on the API spec that could create this behavior? We would appreciate a lot if you could help us to fix this error.

It's worth noting that we upgraded our cvpysdk version to 11.30.1

Kind regards

**Comment by spakhare** [comment]
Hi @computeroregano,

Can you please raise a commvault support ticket for this? We would need logs on the CommServ & Webserver to check this further.

Thanks
