### ISSUE TITLE
schedule.run_now() only returns one jobid

### ISSUE THREAD

**Issue by rfx77** [Commvault/cvpysdk#171]
When more then on job is started by schedule.run_now() only the first jobid is returned. please fix this or provide an optional parameter tu return a list of jobids.

resulting json:
`{'processinginstructioninfo': {'attributes': [{'name': 'WebServer', 'value': 'PINF05'}]}, 'jobIds': ['225990', '225991', '225992']}`

return from function: 225990

**Comment by rfx77** [comment]
Here would be the code of the new method:

Maybe someone could check this.

```
    def run_now(self, return_multiple=False):
        """
        Triggers the schedule to run immediately

        Returns: job id
        """
        request_json = {
            "TMMsg_TaskOperationReq":
                {
                    "opType": 5,
                    "subtaskEntity":
                        [
                            {
                                "_type_": 68,
                                "subtaskId": self.subtask_id,
                                "taskName": "",
                                "subtaskName": self.schedule_name,
                                "taskId": self.task_id
                            }
                        ],
                    "taskIds":
                        [
                            self.task_id
                        ]
                }
        }

        flag, response = self._commcell_object._cvpysdk_object.make_request(
            'POST', self._MODIFYSCHEDULE, request_json
        )
        if response.json():
            if "jobIds" in response.json():
                if(return_multiple):
                    job_ids = [int(i) for i in response.json()['jobIds']]
                else:
                    job_id = str(response.json()["jobIds"][0])


                return job_id
            else:
                raise SDKException(
                    'Response', '102', 'JobID not found in response')
        else:
            raise SDKException('Response', '102')


```

**Comment by vinudass** [comment]
this is expected to trigger one report job only, can you share details and request json on how you are triggering multiple jobs using this.

**Comment by rfx77** [comment]
with schedulepolicy.run_now() you dont start reports. you start a schedule-policy in commvault. within this schedulepolicy various jobs can be started. ist depends on the subclientens which are associated with the scheduel-policy. 

eg.: you can associate all auxcopys with one schedule policy (which is default). when you do run_now() all auxcopy-jobs will be started. so you have to return all jobids and not only one of the jobids.

my code above is tested and works correctly.

**Comment by spakhare** [comment]
This should be available with the latest version on the dev branch.
https://github.com/Commvault/cvpysdk/blob/dev/cvpysdk/schedules.py#L2268
