### ISSUE TITLE
Feature: resync clientgroups

### ISSUE THREAD

**Issue by intervisionlord** [Commvault/cvpysdk#172]
Please add a method for clientgroup class for manualy resync clients in clientgroup

Reason:

```
def sync(group_name: str) -> None:
    target_group = ClientGroup(commcell, group_name)
    target_group.update_properties({'syncStatus': 1})
    print('NEW Sync Status:', target_group.properties['discoverRulesInfo']['syncStatus'])
    print('Clients', target_group.associated_clients)
```
Returns:
```
NEW Sync Status: 0
Clients []
```

Seems it does not work

**Comment by spakhare** [comment]
A new method to refresh the associated clients is added.

https://github.com/Commvault/cvpysdk/blob/dev/cvpysdk/clientgroup.py#L2036

Thanks,
