### ISSUE TITLE
Syntax error in plan.py

### ISSUE THREAD

**Issue by intervisionlord** [Commvault/cvpysdk#178]
https://github.com/Commvault/cvpysdk/blob/f768586c443246b3f15ea9e0ce54ee301edc6c1c/cvpysdk/plan.py#L245

```
cvpysdk/plan.py", line 245
    if region_name := copy_details.get("region_name"):
                    ^
SyntaxError: invalid syntax
```

Python 3.6
walrus operators anounced in python 3.8

cvpysdk compatibility declared as Python 3.6 and above

**Comment by spakhare** [comment]
Hi @intervisionlord,

Can you please try using Python 3.9 or higher? We have updated our supported Python version in our Readme.

Thanks

**Comment by intervisionlord** [comment]
uh... sad story (i used 3.11, but our production environment only 3.6 right now)
well... thanks for clarify.
