### ISSUE TITLE
Changing client description modifies additional settings

### ISSUE THREAD

**Issue by lwolfs66** [Commvault/cvpysdk#179]
When I change a client description using the following code:

```python
commcell = Commcell(commvault_server, authtoken=token)
client_name = 'cvclient001'
new_description = 'Test Client zero-one'
client = commcell.clients.get(client_name)
client_properties = client.properties
client_properties['client']['clientDescription'] = new_description
client.update_properties(client_properties)
```

additional setting inherited from client group is modified from _groupname_ to **This Object**.
This behaviour is unwanted to my opinion.

CC = 11.32.69
cvpysdk version is 11.36.1

**Comment by spakhare** [comment]
Please try using the below request to update the description.

client_properties = {
    "clientProperties": {
        "client": {
            "clientDescription": new_description
        }
    }
}
client.update_properties(client_properties)

**Comment by lwolfs66** [comment]
Thx Spakhare for your comment.

Unfortunately the script didnt do anything after adding the client_properties

**Comment by spakhare** [comment]
My bad, Looks like we don't need the root key. Can you please try with below one?

    update_description = {
        "client": {
          "clientDescription": description
        }
      }
      self.update_properties(update_description)

**Comment by lwolfs66** [comment]
Yep...This one is only changing the client description.  Audit trail confirms :-)
